// **************************************************************************
//		Copyright (c) Microsoft Corporation.
//
// @File:	smoevt.txt
// @Owner: 	macies
//
// Description:
//
//		This is a template file used by smoevt.pl to autogenerate smoevt.cs.
//
// Notes:
@@@ autogenerated
//
// History:
//		
//		@Version: Yukon
//		000000 MJW  09/10/03 ...
//		
// @EndHeader@
// **************************************************************************

using System;
using System.Collections;
using System.Collections.Specialized;
using System.Text;

namespace Microsoft.SqlServer.Management.Smo
{
	// **************************************************************************
	//
	//				CLASSES
	//
	// **************************************************************************

	internal partial class PostProcessServerDdlTriggerEvents : PostProcessDdlEvents
	{

		private ServerDdlTriggerEvent ServerDdlTriggerEventOffsetFromEventString(string evtdesc)
		{
			switch (evtdesc)
			{
@@@ServerDdlTriggerEvent_string_offset_mapping
			}
			return ServerDdlTriggerEvent.CreateEndpoint;
		}
	}

	internal partial class PostProcessDatabaseDdlTriggerEvents : PostProcessDdlEvents
	{

		private DatabaseDdlTriggerEvent DatabaseDdlTriggerEventOffsetFromEventString(string evtdesc)
		{
			switch (evtdesc)
			{
@@@DatabaseDdlTriggerEvent_string_offset_mapping
			}

		return DatabaseDdlTriggerEvent.CreateTable;
		}
	}

	// From here on generated template code
@@@CLASS_TEMPLATE
	// End of generated template code


}
