
 ///////////////////////////////////////////////////////////////
 //
 // WARNING : DO NOT ATTEMPT TO MODIFY THIS FILE MANUALLY
 // 
 // This class is autogenerated from generic_collection.cs
 //
 ///////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Specialized;
using System.Text;
using System.Globalization;
#pragma warning disable 1590,1591,1592,1573,1571,1570,1572,1587



using Microsoft.SqlServer.Management.Sdk.Sfc;


























	



namespace Microsoft.SqlServer.Management.Smo
{

	///<summary>
	/// Strongly typed list of MAPPED_TYPE objects
	/// Has strongly typed support for all of the methods of the sorted list class
	///</summary>
	public sealed  class EdgeCollection : SimpleObjectCollectionBase
	{


















		internal EdgeCollection(SqlSmoObject parentInstance)  : base(parentInstance)
		{
		}



		public SqlSmoObject Parent
		{
			get
			{
				return this.ParentInstance as SqlSmoObject;
			}
		}

		
		public Edge this[Int32 index]
		{
			get
			{ 
				return GetObjectByIndex(index) as Edge;
			}
		}


		// returns wrapper class
		public Edge this[string name]
		{
			get
			{
                





    
	    			    return  GetObjectByName(name) as Edge;
                    
                



















			}
		}


		public void CopyTo(Edge[] array, int index)
		{
			((ICollection)this).CopyTo(array, index);
		}
		

		public Edge ItemById(int id)
		{
			return (Edge)GetItemById(id);
		}


































		protected override Type GetCollectionElementType()
		{
			return typeof(Edge);
		}

		internal override SqlSmoObject GetCollectionElementInstance(ObjectKeyBase key, SqlSmoState state)
		{
			return  new Edge(this, key, state);
		}




		public void Remove(Edge edge)
		{
			if( null == edge )
				throw new FailedOperationException(ExceptionTemplates.RemoveCollection, this, new ArgumentNullException("edge"));
			
			RemoveObj(edge, new SimpleObjectKey(edge.Name));
		}

		public void Remove(string name)
		{
			this.Remove(new SimpleObjectKey(name));
		}



		public void Add(Edge edge) 
		{
			AddImpl(edge);
		}


		internal SqlSmoObject GetObjectByName(string name)
		{
			return GetObjectByKey(new SimpleObjectKey(name));
		}


		internal override ObjectKeyBase CreateKeyFromUrn(Urn urn)
		{ 
			string name = urn.GetAttribute("Name");



            if( null == name || name.Length == 0)

				throw new SmoException(ExceptionTemplates.PropertyMustBeSpecifiedInUrn("Name", urn.Type));
            return new SimpleObjectKey(name);        
        }


















	}
}
