
 ///////////////////////////////////////////////////////////////
 //
 // Copyright (c) Microsoft.
 // Licensed under the MIT license.
 // WARNING : DO NOT ATTEMPT TO MODIFY THIS FILE MANUALLY
 // 
 // This class is autogenerated from generic_collection.cs
 //
 ///////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Specialized;
using System.Text;
using System.Globalization;



using Microsoft.SqlServer.Management.Sdk.Sfc;































	



namespace Microsoft.SqlServer.Management.Smo
{

	///<summary>
	/// Strongly typed list of SensitivityClassification objects
	/// Has strongly typed support for all of the methods of the sorted list class
	///</summary>
	public sealed  class SensitivityClassificationCollection : SimpleObjectCollectionBase
	{


















		internal SensitivityClassificationCollection(SqlSmoObject parentInstance)  : base(parentInstance)
		{
		}



		public SqlSmoObject Parent
		{
			get
			{
				return this.ParentInstance as SqlSmoObject;
			}
		}

		
		public SensitivityClassification this[Int32 index]
		{
			get
			{ 
				return GetObjectByIndex(index) as SensitivityClassification;
			}
		}


		// returns wrapper class
		public SensitivityClassification this[string name]
		{
			get
			{
                





    
	    			    return  GetObjectByName(name) as SensitivityClassification;
                    
                



















			}
		}


		public void CopyTo(SensitivityClassification[] array, int index)
		{
			((ICollection)this).CopyTo(array, index);
		}
		

		public SensitivityClassification ItemById(int id)
		{
			return (SensitivityClassification)GetItemById(id);
		}


































		protected override Type GetCollectionElementType()
		{
			return typeof(SensitivityClassification);
		}

		internal override SqlSmoObject GetCollectionElementInstance(ObjectKeyBase key, SqlSmoState state)
		{
			return  new SensitivityClassification(this, key, state);
		}



















		public void Add(SensitivityClassification SensitivityClassification) 
		{
			AddImpl(SensitivityClassification);
		}


		internal SqlSmoObject GetObjectByName(string name)
		{
			return GetObjectByKey(new SimpleObjectKey(name));
		}


		internal override ObjectKeyBase CreateKeyFromUrn(Urn urn)
		{ 
			string name = urn.GetAttribute("Name");



            if( null == name || name.Length == 0)

				throw new SmoException(ExceptionTemplates.PropertyMustBeSpecifiedInUrn("Name", urn.Type));
            return new SimpleObjectKey(name);        
        }


















	}
}
