 ///////////////////////////////////////////////////////////////
 //
 // Copyright (c) Microsoft Corporation.
 // Licensed under the MIT license.
 // WARNING : DO NOT ATTEMPT TO MODIFY THIS FILE MANUALLY
 // 
 // This class is autogenerated from numbered_generic_collection.cs
 //
 ///////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Specialized;
using System.Text;

#include "coll_macros.h"

namespace NAMESPACE_NAME
{

	///<summary>
	/// Strongly typed list of MAPPED_TYPE objects
	/// Has strongly typed support for all of the methods of the sorted list class
	///</summary>
	public SEALED_IMP PARTIAL_KEYWORD class TOKEN_PASTE( MAPPED_TYPE, COLLECTION_SUFFIX) : 
#ifdef PHYSICAL_PARTITION
        PartitionNumberedObjectCollectionBase
#else       
        NumberedObjectCollectionBase
#endif 
	{

		internal TOKEN_PASTE( MAPPED_TYPE, COLLECTION_SUFFIX)(SqlSmoObject parentInstance)  : base(parentInstance)
		{
		}

#ifdef PARENT
		public PARENT Parent
		{
			get
			{
				return this.ParentInstance as PARENT;
			}
		}
#endif
		
#ifdef PHYSICAL_PARTITION
        public void Add(MAPPED_TYPE MAPPED_TYPE_VAR)
        {
            InternalStorage.Add(new PartitionNumberedObjectKey((short)MAPPED_TYPE_VAR.PartitionNumber),MAPPED_TYPE_VAR);
        }

        public void Remove(MAPPED_TYPE MAPPED_TYPE_VAR)
        {
            InternalStorage.Remove(new PartitionNumberedObjectKey((short)MAPPED_TYPE_VAR.PartitionNumber));
        }
        public void Remove(Int32 partitionNumber)
        {
            InternalStorage.Remove(new PartitionNumberedObjectKey((short)partitionNumber));
        }

#endif //PHYSICAL_PARTITION

       

		public MAPPED_TYPE this[Int32 index]
		{
			get
			{ 
			    return GetObjectByIndex(index) as MAPPED_TYPE;
			}
		}

		protected override Type GetCollectionElementType()
		{
			return typeof(MAPPED_TYPE);
		}

		internal override SqlSmoObject GetCollectionElementInstance(ObjectKeyBase key, SqlSmoState state)
		{
			return  new MAPPED_TYPE(this, key, state);
		}

#ifndef PHYSICAL_PARTITION
		public MAPPED_TYPE GetProcedureByNumber(short number)
		{
			return GetObjectByKey(new NumberedObjectKey(number)) as MAPPED_TYPE;
		}

        public void CopyTo(MAPPED_TYPE[] array, int index)
		{
			((ICollection)this).CopyTo(array, index);
		}
		
#endif //PHYSICAL_PARTITION
	}
}
