 ///////////////////////////////////////////////////////////////
 // Copyright (c) Microsoft.
 // Licensed under the MIT license.
 //
 // WARNING : DO NOT ATTEMPT TO MODIFY THIS FILE MANUALLY
 // 
 // This classes is autogenerated from schedule_generic_collection.cs
 //
 ///////////////////////////////////////////////////////////////

using System;
using System.Data;
using System.Collections;

#include "coll_macros.h"

namespace NAMESPACE_NAME
{

	///<summary>
	/// Strongly typed collection of MAPPED_TYPE objects
	/// Supports indexing objects by their Name and Schema properties
	///</summary>
	public SEALED_IMP class TOKEN_PASTE( MAPPED_TYPE, COLLECTION_SUFFIX) : JobScheduleCollectionBase
	{

		internal TOKEN_PASTE( MAPPED_TYPE, COLLECTION_SUFFIX)(SqlSmoObject parentInstance)  : base(parentInstance)
		{
		}

#ifdef PARENT
		public PARENT Parent
		{
			get
			{
				return this.ParentInstance as PARENT;
			}
		}
#endif

		public MAPPED_TYPE this[Int32 index]
		{
			get
			{ 
				return GetObjectByIndex(index) as MAPPED_TYPE;
			}
		}

		public MAPPED_TYPE this[KEY_TYPE name]
		{
			get
			{
				return GetObjectByKey(new ScheduleObjectKey(name, GetDefaultID())) as MAPPED_TYPE;
			}
		}

		public void CopyTo(MAPPED_TYPE[] array, int index)
		{
			((ICollection)this).CopyTo(array, index);
		}

		public MAPPED_TYPE ItemById(int id)
		{
			IEnumerator ie = ((IEnumerable)this).GetEnumerator();
			while (ie.MoveNext())
			{
				MAPPED_TYPE c = (MAPPED_TYPE)ie.Current;

				if (c.ID == id) // found object with the right id
					return c;
			}
			return null;

		}

		protected override Type GetCollectionElementType()
		{
			return typeof(MAPPED_TYPE);
		}

		internal override SqlSmoObject GetCollectionElementInstance(ObjectKeyBase key, SqlSmoState state)
		{
			return new MAPPED_TYPE(this, key, state);
		}

#ifdef ADD_REMOVE
			public void Add(MAPPED_TYPE MAPPED_TYPE_VAR) 
			{
				if( null == MAPPED_TYPE_VAR )
					throw new FailedOperationException(ExceptionTemplates.AddCollection, this, new ArgumentNullException(STRINGER(MAPPED_TYPE_VAR)));
			
				AddImpl(MAPPED_TYPE_VAR);
			}

			public void Remove(MAPPED_TYPE MAPPED_TYPE_VAR)
			{
				if( null == MAPPED_TYPE_VAR )
					throw new FailedOperationException(ExceptionTemplates.RemoveCollection, this, new ArgumentNullException(STRINGER(MAPPED_TYPE_VAR)));
			
				RemoveObj(MAPPED_TYPE_VAR, new ScheduleObjectKey(MAPPED_TYPE_VAR.Name, MAPPED_TYPE_VAR.Schema));
			}

			public void Remove(string name)
			{
				this.Remove(new ScheduleObjectKey(name, GetDefaultID()));
			}
#endif // ADD_REMOVE
		
		internal SqlSmoObject GetObjectByName(string name)
		{
			return GetObjectByKey(new ScheduleObjectKey(name, GetDefaultID()));
		}

	}
}
