//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.Management.HadrModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.Management.HadrModel.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding database credential for &apos;{0}&apos; on &apos;{1}&apos;..
        /// </summary>
        internal static string AddDatabaseCredentialText {
            get {
                return ResourceManager.GetString("AddDatabaseCredentialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding databases to availability group &apos;{0}&apos;..
        /// </summary>
        internal static string AddDatabaseToExistingAvailabilityGroupText {
            get {
                return ResourceManager.GetString("AddDatabaseToExistingAvailabilityGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Domain User In Admin Group Fail, Domain User Name {0}.
        /// </summary>
        internal static string AddDomainUserInAdminGroupTaskException {
            get {
                return ResourceManager.GetString("AddDomainUserInAdminGroupTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the domain user &apos;{0}&apos; to Windows administrators group..
        /// </summary>
        internal static string AddDomainUserInAdminGroupText {
            get {
                return ResourceManager.GetString("AddDomainUserInAdminGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Domain To Service Account Fail, Domain User Name {0} Domain User Password {1}.
        /// </summary>
        internal static string AddDomainUserInSQLAdminTaskAddDomainAccountToServiceAccountException {
            get {
                return ResourceManager.GetString("AddDomainUserInSQLAdminTaskAddDomainAccountToServiceAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User To Sql Admin Fail, User Name: {0}.
        /// </summary>
        internal static string AddDomainUserInSQLAdminTaskAddUserToSqlAdminException {
            get {
                return ResourceManager.GetString("AddDomainUserInSQLAdminTaskAddUserToSqlAdminException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the domain user &apos;{0}&apos; to SQL Server administrators group..
        /// </summary>
        internal static string AddDomainUserInSQLAdminText {
            get {
                return ResourceManager.GetString("AddDomainUserInSQLAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster {0} is Not Online, Domain User Name {1}, Domain User Password{2}.
        /// </summary>
        internal static string AddNodeInClusterTaskClusterNotOnlineException {
            get {
                return ResourceManager.GetString("AddNodeInClusterTaskClusterNotOnlineException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding node &apos;{0}&apos; in cluster &apos;{1}&apos;..
        /// </summary>
        internal static string AddNodeInClusterText {
            get {
                return ResourceManager.GetString("AddNodeInClusterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNodeInClusterVerificationError Machie Name {0}.
        /// </summary>
        internal static string AddNodeInClusterVerificationError {
            get {
                return ResourceManager.GetString("AddNodeInClusterVerificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding replica to availability group &apos;{0}&apos;..
        /// </summary>
        internal static string AddReplicaText {
            get {
                return ResourceManager.GetString("AddReplicaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Group Does Not Exist :Group Name:{0}, Server Name {1}.
        /// </summary>
        internal static string AvailabilityGroupNotExists {
            get {
                return ResourceManager.GetString("AvailabilityGroupNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability group {0} is not joined on the secondary replica {1}..
        /// </summary>
        internal static string AvailabilityGroupNotJoined {
            get {
                return ResourceManager.GetString("AvailabilityGroupNotJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quorum vote configuration fails, AG Name{0}.
        /// </summary>
        internal static string AvailabilityGroupQuorumValidatorException {
            get {
                return ResourceManager.GetString("AvailabilityGroupQuorumValidatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the secondary replicas can be in synchronous commit mode when the primary replica is in asynchronous commit mode..
        /// </summary>
        internal static string AvailabilityModeCompatibilityWarning {
            get {
                return ResourceManager.GetString("AvailabilityModeCompatibilityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database {0} fail.
        /// </summary>
        internal static string BackupDatabaseTaskException {
            get {
                return ResourceManager.GetString("BackupDatabaseTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a full backup for &apos;{0}&apos;..
        /// </summary>
        internal static string BackupDatabaseText {
            get {
                return ResourceManager.GetString("BackupDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup location is not provided.
        /// </summary>
        internal static string BackupLocationNotProvidedErrorMessage {
            get {
                return ResourceManager.GetString("BackupLocationNotProvidedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database {0} Log fail.
        /// </summary>
        internal static string BackupLogTaskException {
            get {
                return ResourceManager.GetString("BackupLogTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backing up log for &apos;{0}&apos;..
        /// </summary>
        internal static string BackupLogText {
            get {
                return ResourceManager.GetString("BackupLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current configuration is not compatible with BASIC Availability Groups: {0}..
        /// </summary>
        internal static string BasicAvailabilityGroupIncompatibleException {
            get {
                return ResourceManager.GetString("BasicAvailabilityGroupIncompatibleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC Availability Groups only support a Backup Priority of 50..
        /// </summary>
        internal static string BasicBackupPriorityReason {
            get {
                return ResourceManager.GetString("BasicBackupPriorityReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC Availability Groups do not support Listeners..
        /// </summary>
        internal static string BasicListenerReason {
            get {
                return ResourceManager.GetString("BasicListenerReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC Availability Groups do not support readable secondary replicas..
        /// </summary>
        internal static string BasicSecondaryRoleReason {
            get {
                return ResourceManager.GetString("BasicSecondaryRoleReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC Availability Groups only support up to one database per availability group..
        /// </summary>
        internal static string BasicTooManyDatabasesReason {
            get {
                return ResourceManager.GetString("BasicTooManyDatabasesReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC Availability Groups only support up to two replicas (one primary and one secondary) per availability group..
        /// </summary>
        internal static string BasicTooManyReplicasReason {
            get {
                return ResourceManager.GetString("BasicTooManyReplicasReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the listener configuration.
        /// </summary>
        internal static string CheckingListenerConfiguration {
            get {
                return ResourceManager.GetString("CheckingListenerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Server {0} is offline.
        /// </summary>
        internal static string ClusterNameOnlineValidatorException {
            get {
                return ResourceManager.GetString("ClusterNameOnlineValidatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring endpoints..
        /// </summary>
        internal static string ConfigureEndpointsText {
            get {
                return ResourceManager.GetString("ConfigureEndpointsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail To Enable Always On for Instance {0}.
        /// </summary>
        internal static string ConfigureSQLForAlwaysonTaskException {
            get {
                return ResourceManager.GetString("ConfigureSQLForAlwaysonTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectRemotePowersehllError.
        /// </summary>
        internal static string ConnectRemotePowersehllError {
            get {
                return ResourceManager.GetString("ConnectRemotePowersehllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Availability Group Listener &apos;{0}&apos;..
        /// </summary>
        internal static string CreateAvailabilityGroupListenerText {
            get {
                return ResourceManager.GetString("CreateAvailabilityGroupListenerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating availability group &apos;{0}&apos;..
        /// </summary>
        internal static string CreateAvailabilityGroupText {
            get {
                return ResourceManager.GetString("CreateAvailabilityGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Login on replica &apos;{0}&apos;..
        /// </summary>
        internal static string CreateLoginText {
            get {
                return ResourceManager.GetString("CreateLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup task failed to execute create &apos;{0}&apos; storage service..
        /// </summary>
        internal static string CreateStorageServiceNoStatusException {
            get {
                return ResourceManager.GetString("CreateStorageServiceNoStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create storage service {0} failed with following error {1}..
        /// </summary>
        internal static string CreateStorageServiceStatusFailException {
            get {
                return ResourceManager.GetString("CreateStorageServiceStatusFailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1}.
        /// </summary>
        internal static string CreateVirtualDisk2 {
            get {
                return ResourceManager.GetString("CreateVirtualDisk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Availability Group with name {0}..
        /// </summary>
        internal static string CreatingAvailabilityGroup {
            get {
                return ResourceManager.GetString("CreatingAvailabilityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating logins {0} on replica {1}..
        /// </summary>
        internal static string CreatingLoginsOnReplica {
            get {
                return ResourceManager.GetString("CreatingLoginsOnReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Disk size upper limit reached: Replica Name {0}, Replica Database key {1} Limit {2}.
        /// </summary>
        internal static string DataBaseDiskSizeValidationException {
            get {
                return ResourceManager.GetString("DataBaseDiskSizeValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following required directories do not exist on replica {0} : {1}..
        /// </summary>
        internal static string DatabaseFileLocationMissingOnReplicaException {
            get {
                return ResourceManager.GetString("DatabaseFileLocationMissingOnReplicaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some database files are not in the default directories. Default data directory: &apos;{0}&apos;. Default log directory: &apos;{1}&apos;. Files not in default directories: &apos;{2}&apos;..
        /// </summary>
        internal static string DatabaseFileNotInDefaultDirectoryException {
            get {
                return ResourceManager.GetString("DatabaseFileNotInDefaultDirectoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The databases {1} already exist on secondary {0}..
        /// </summary>
        internal static string DatabasesExistingOnReplica {
            get {
                return ResourceManager.GetString("DatabasesExistingOnReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the database master key is incorrect..
        /// </summary>
        internal static string DBMKPasswordIncorrect {
            get {
                return ResourceManager.GetString("DBMKPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Deployment {1} failed . Hosted Service Name {0}.
        /// </summary>
        internal static string DeleteDeploymentNoStatusException {
            get {
                return ResourceManager.GetString("DeleteDeploymentNoStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Deployment {1} failed . Hosted Service Name {0}, detail: {2}.
        /// </summary>
        internal static string DeleteDeploymentStatusFailException {
            get {
                return ResourceManager.GetString("DeleteDeploymentStatusFailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete hosted service {0} failed ..
        /// </summary>
        internal static string DeleteHostedServiceNoStatusException {
            get {
                return ResourceManager.GetString("DeleteHostedServiceNoStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete hosted service {0} failed with following error {1}..
        /// </summary>
        internal static string DeleteHostedServiceStatusFailException {
            get {
                return ResourceManager.GetString("DeleteHostedServiceStatusFailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete storage service {0} failed ..
        /// </summary>
        internal static string DeleteStorageServiceNoStatusException {
            get {
                return ResourceManager.GetString("DeleteStorageServiceNoStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete storage service {0} failed with following error {1}..
        /// </summary>
        internal static string DeleteStorageServiceStatusFailException {
            get {
                return ResourceManager.GetString("DeleteStorageServiceStatusFailException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Virtual Machine Failed{2}, Hosted Service Name :{0}, Deployment Name: {1}.
        /// </summary>
        internal static string DeleteVirtualMachineNoStatusException {
            get {
                return ResourceManager.GetString("DeleteVirtualMachineNoStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Virtual Machine Failed{2}, Hosted Service Name :{0}, Deployment Name: {1},Detail :{3}.
        /// </summary>
        internal static string DeleteVirtualMachineStatusException {
            get {
                return ResourceManager.GetString("DeleteVirtualMachineStatusException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostedService:{0} ,Deployment Counts:{1}.
        /// </summary>
        internal static string DeploymentHealthyValidationDeploymentNotAvailableException {
            get {
                return ResourceManager.GetString("DeploymentHealthyValidationDeploymentNotAvailableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment {0} does not exist..
        /// </summary>
        internal static string DeploymentNotExistException {
            get {
                return ResourceManager.GetString("DeploymentNotExistException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Virtual Network: {0},Deployment Virtual Network:{1}.
        /// </summary>
        internal static string DeploymentVirtualNetworkConfigurationVirtualNetworkNotMatchException {
            get {
                return ResourceManager.GetString("DeploymentVirtualNetworkConfigurationVirtualNetworkNotMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find drive letter &apos;{0}&apos; on replica &apos;{1}&apos;..
        /// </summary>
        internal static string DriveNotFoundOnReplica {
            get {
                return ResourceManager.GetString("DriveNotFoundOnReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Windows Server Failover Cluster failed, OS Version {0}.
        /// </summary>
        internal static string EnableWindowsFailoverClusterTaskException {
            get {
                return ResourceManager.GetString("EnableWindowsFailoverClusterTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling {0} Xevent to autostart on replica {1}..
        /// </summary>
        internal static string EnablingXeventOnReplica {
            get {
                return ResourceManager.GetString("EnablingXeventOnReplica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration of endpoint data encryption is incompatible between replicas and the endpoint connection will fail. \r\n {0}.
        /// </summary>
        internal static string EncryptionMismatchException {
            get {
                return ResourceManager.GetString("EncryptionMismatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint {0} uses {1} Authentication, only Negotiate authentication for WA replica is allowed.
        /// </summary>
        internal static string EndpointAuthenticationValidatorException {
            get {
                return ResourceManager.GetString("EndpointAuthenticationValidatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica {0} is a {1}, can not failover to this replica..
        /// </summary>
        internal static string FailoverValidationException {
            get {
                return ResourceManager.GetString("FailoverValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is updated to {1}..
        /// </summary>
        internal static string FieldSetUpdate {
            get {
                return ResourceManager.GetString("FieldSetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing forced failover to secondary replica &apos;{0}&apos;.
        /// </summary>
        internal static string ForcedFailoverTaskText {
            get {
                return ResourceManager.GetString("ForcedFailoverTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Data Disk Error: ResFile {0}, Disk Label{1} .
        /// </summary>
        internal static string FormatDataDiskTaskException {
            get {
                return ResourceManager.GetString("FormatDataDiskTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the free space in the drive corresponding to the data-file {0} on replica {1}..
        /// </summary>
        internal static string FreeSpaceUnavailableForDataFileDrive {
            get {
                return ResourceManager.GetString("FreeSpaceUnavailableForDataFileDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the free space in the drive corresponding to the log-file {0} on replica {1}..
        /// </summary>
        internal static string FreeSpaceUnavailableForLogFileDrive {
            get {
                return ResourceManager.GetString("FreeSpaceUnavailableForLogFileDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Affinity Group: {0},Hosted Service Affinity Group:{1}.
        /// </summary>
        internal static string HostedServiceAffinityGroupConfigurationAffinityGroupNotMatchException {
            get {
                return ResourceManager.GetString("HostedServiceAffinityGroupConfigurationAffinityGroupNotMatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string ImageArgumentNullException {
            get {
                return ResourceManager.GetString("ImageArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image name.
        /// </summary>
        internal static string ImageNameArgumentNullException {
            get {
                return ResourceManager.GetString("ImageNameArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient free space for data and log files on the server instance that hosts secondary replica {0}.
        /// </summary>
        internal static string InSufficientFreeSpaceForDataFiles {
            get {
                return ResourceManager.GetString("InSufficientFreeSpaceForDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient free space for log files on the server instance that hosts secondary replica {0}..
        /// </summary>
        internal static string InSufficientFreeSpaceForLogFiles {
            get {
                return ResourceManager.GetString("InSufficientFreeSpaceForLogFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Group with name {0} not found on server {1}..
        /// </summary>
        internal static string InvalidAvailabilityGroupException {
            get {
                return ResourceManager.GetString("InvalidAvailabilityGroupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid shared network location..
        /// </summary>
        internal static string InvalidShare {
            get {
                return ResourceManager.GetString("InvalidShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to join availability group resulted in an error..
        /// </summary>
        internal static string JoinAvailabilityGroupError {
            get {
                return ResourceManager.GetString("JoinAvailabilityGroupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining &apos;{0}&apos; to availability group &apos;{1}&apos; on &apos;{2}&apos;..
        /// </summary>
        internal static string JoinDatabaseToAvailabilityGroupText {
            get {
                return ResourceManager.GetString("JoinDatabaseToAvailabilityGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining secondaries to availability group &apos;{0}&apos;..
        /// </summary>
        internal static string JoinSecondariesText {
            get {
                return ResourceManager.GetString("JoinSecondariesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listener is not configured for the availability group. Either configure the listener now on the Specify Replicas page, or use the Add Availability Group Listener dialog after the wizard has completed..
        /// </summary>
        internal static string ListenerConfigurationWarning {
            get {
                return ResourceManager.GetString("ListenerConfigurationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing manual failover to secondary replica &apos;{0}&apos;.
        /// </summary>
        internal static string ManualFailoverTaskText {
            get {
                return ResourceManager.GetString("ManualFailoverTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} Hosted Service, reaches the Max Hosted Service.
        /// </summary>
        internal static string MaxHostedServicesException {
            get {
                return ResourceManager.GetString("MaxHostedServicesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not support AG.
        /// </summary>
        internal static string NoAGSupportImageException {
            get {
                return ResourceManager.GetString("NoAGSupportImageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Storage Service is found for {0}  with Virtual Network Location Hash ID {1}.
        /// </summary>
        internal static string NoStorageServiceWithServiceNameAndAffinityGroupNameException {
            get {
                return ResourceManager.GetString("NoStorageServiceWithServiceNameAndAffinityGroupNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Storage Service is found for {0}.
        /// </summary>
        internal static string NoStorageServiceWithServiceNameException {
            get {
                return ResourceManager.GetString("NoStorageServiceWithServiceNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a Sql Server Image.
        /// </summary>
        internal static string NotSqlServerImageException {
            get {
                return ResourceManager.GetString("NotSqlServerImageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Port {0} fail.
        /// </summary>
        internal static string OpenFireWallPortsException {
            get {
                return ResourceManager.GetString("OpenFireWallPortsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The primary server &apos;{0}&apos; cannot write to &apos;{1}&apos;..
        /// </summary>
        internal static string PrimaryCannotWriteToLocation {
            get {
                return ResourceManager.GetString("PrimaryCannotWriteToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling Always On Availability Groups requires that the server instance is hosted by a Windows Server Failover Cluster (WSFC) node.  The Always On Availability Groups feature must be enabled for server instance &apos;{0}&apos; before you can create an availability group on this instance. To enable this feature, open the SQL Server Configuration Manager, select SQL Server Services, right-click on the SQL Server service name, select Properties, and use the Always On High Availability tab of the Server Properties dialo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrimaryServerNotHadrEnabled {
            get {
                return ResourceManager.GetString("PrimaryServerNotHadrEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica {0} does not have a quorum vote.
        /// </summary>
        internal static string QuorumHelperException {
            get {
                return ResourceManager.GetString("QuorumHelperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating Windows Server Failover Cluster quorum vote configuration..
        /// </summary>
        internal static string QuorumValidationTaskText {
            get {
                return ResourceManager.GetString("QuorumValidationTaskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}, {2}, {3}\r\n.
        /// </summary>
        internal static string ReplicaEndpointStringOutputFormat {
            get {
                return ResourceManager.GetString("ReplicaEndpointStringOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to restart Sql Server {0}.
        /// </summary>
        internal static string RestartSqlServerException {
            get {
                return ResourceManager.GetString("RestartSqlServerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database {0} fail.
        /// </summary>
        internal static string RestoreDatabaseTaskExcption {
            get {
                return ResourceManager.GetString("RestoreDatabaseTaskExcption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring &apos;{0}&apos; on &apos;{1}&apos;..
        /// </summary>
        internal static string RestoreDatabaseText {
            get {
                return ResourceManager.GetString("RestoreDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Database {0} log Fail.
        /// </summary>
        internal static string RestoreLogTaskException {
            get {
                return ResourceManager.GetString("RestoreLogTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring &apos;{0}&apos; log on &apos;{1}&apos;..
        /// </summary>
        internal static string RestoreLogText {
            get {
                return ResourceManager.GetString("RestoreLogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secondary server &apos;{0}&apos; cannot read from &apos;{1}&apos;..
        /// </summary>
        internal static string SecondaryCannotReadLocation {
            get {
                return ResourceManager.GetString("SecondaryCannotReadLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationId={0}, Status={1}, Code={2}.
        /// </summary>
        internal static string ServiceOperationStateFailedMsg3 {
            get {
                return ResourceManager.GetString("ServiceOperationStateFailedMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationId={0}, Status={1}, Code={2}, Details={3}.
        /// </summary>
        internal static string ServiceOperationStateFailedMsg4 {
            get {
                return ResourceManager.GetString("ServiceOperationStateFailedMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null statu.
        /// </summary>
        internal static string ServiceOperationStatusArgumentNullException {
            get {
                return ResourceManager.GetString("ServiceOperationStatusArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the &apos;{0}&apos; extended events session on &apos;{1}&apos;..
        /// </summary>
        internal static string StartAlwaysOnXeventSessionText {
            get {
                return ResourceManager.GetString("StartAlwaysOnXeventSessionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscription.
        /// </summary>
        internal static string SubscriptionArgumentNullException {
            get {
                return ResourceManager.GetString("SubscriptionArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation task completed.
        /// </summary>
        internal static string TaskEventArgsTaskComplete {
            get {
                return ResourceManager.GetString("TaskEventArgsTaskComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Cancelled by User.
        /// </summary>
        internal static string TaskEventArgsTaskExecutionCancelled {
            get {
                return ResourceManager.GetString("TaskEventArgsTaskExecutionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed due to following error: {0}.
        /// </summary>
        internal static string TaskEventArgsTaskExecutionFailed {
            get {
                return ResourceManager.GetString("TaskEventArgsTaskExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed due to following error: {0}, retrying .....
        /// </summary>
        internal static string TaskEventArgsTaskExecutionFailedWithRetry {
            get {
                return ResourceManager.GetString("TaskEventArgsTaskExecutionFailedWithRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task started .....
        /// </summary>
        internal static string TaskEventArgsTaskStarted {
            get {
                return ResourceManager.GetString("TaskEventArgsTaskStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total databases size upper limit reached: Limit:{0} GB, Total:{1} MB.
        /// </summary>
        internal static string TotalPrimaryDatabaseSizeValidationException {
            get {
                return ResourceManager.GetString("TotalPrimaryDatabaseSizeValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating availability group listener &apos;{0}&apos;..
        /// </summary>
        internal static string UpdateAvailabilityGroupListenerText {
            get {
                return ResourceManager.GetString("UpdateAvailabilityGroupListenerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to perform this action..
        /// </summary>
        internal static string UserDoesNotHaveViewServerStatePermission {
            get {
                return ResourceManager.GetString("UserDoesNotHaveViewServerStatePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking replica availability mode.
        /// </summary>
        internal static string ValidatingAvailabilityMode {
            get {
                return ResourceManager.GetString("ValidatingAvailabilityMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking shared network location.
        /// </summary>
        internal static string ValidatingBackupLocation {
            get {
                return ResourceManager.GetString("ValidatingBackupLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking compatibility of basic availability group options.
        /// </summary>
        internal static string ValidatingBasicAvailabilityGroupOptions {
            get {
                return ResourceManager.GetString("ValidatingBasicAvailabilityGroupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for the database files on the secondary replica {0} resulted in an error. The following files already exist. {1}.
        /// </summary>
        internal static string ValidatingDatabaseFileExistingError {
            get {
                return ResourceManager.GetString("ValidatingDatabaseFileExistingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for compatibility of the database file locations on the server instance that hosts replica {0}.
        /// </summary>
        internal static string ValidatingDatabaseFileLocationCompatibility {
            get {
                return ResourceManager.GetString("ValidatingDatabaseFileLocationCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for the existence of the database files on the server instance that hosts secondary.
        /// </summary>
        internal static string ValidatingDatabaseFilesNotExistsOnSecondary {
            get {
                return ResourceManager.GetString("ValidatingDatabaseFilesNotExistsOnSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking password of the database master key.
        /// </summary>
        internal static string ValidatingDatabaseMasterKey {
            get {
                return ResourceManager.GetString("ValidatingDatabaseMasterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if the selected databases already exist on the server instance that hosts secondary replica {0}.
        /// </summary>
        internal static string ValidatingDatabaseNotExistOnSecondary {
            get {
                return ResourceManager.GetString("ValidatingDatabaseNotExistOnSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for free disk space on the server instance that hosts secondary replica {0}.
        /// </summary>
        internal static string ValidatingDiskSpace {
            get {
                return ResourceManager.GetString("ValidatingDiskSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the endpoint is encrypted using a compatible algorithm.
        /// </summary>
        internal static string ValidatingEndpointEncryption {
            get {
                return ResourceManager.GetString("ValidatingEndpointEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating failover settings for secondary replica &apos;{0}&apos;.
        /// </summary>
        internal static string ValidatingFailoverSettings {
            get {
                return ResourceManager.GetString("ValidatingFailoverSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating WSFC quorum vote configuration.
        /// </summary>
        internal static string ValidatingWSFCQuorumConfiguration {
            get {
                return ResourceManager.GetString("ValidatingWSFCQuorumConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation task completed.
        /// </summary>
        internal static string ValidatorEventArgsValidationComplete {
            get {
                return ResourceManager.GetString("ValidatorEventArgsValidationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed due to following error: {0}.
        /// </summary>
        internal static string ValidatorEventArgsValidationFailed {
            get {
                return ResourceManager.GetString("ValidatorEventArgsValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed due to following error: {0}, retrying .....
        /// </summary>
        internal static string ValidatorEventArgsValidationFailedWithRetry {
            get {
                return ResourceManager.GetString("ValidatorEventArgsValidationFailedWithRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation started .....
        /// </summary>
        internal static string ValidatorEventArgsValidationStarted {
            get {
                return ResourceManager.GetString("ValidatorEventArgsValidationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualNetworkLocationHashID.
        /// </summary>
        internal static string VirtualNetworkLocationHashIDNullException {
            get {
                return ResourceManager.GetString("VirtualNetworkLocationHashIDNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Availability Group with name {0} to be created..
        /// </summary>
        internal static string WaitForAvailabilityGroupOnline {
            get {
                return ResourceManager.GetString("WaitForAvailabilityGroupOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for availability group &apos;{0}&apos; to come online..
        /// </summary>
        internal static string WaitForAvailabilityGroupOnlineText {
            get {
                return ResourceManager.GetString("WaitForAvailabilityGroupOnlineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing the role change for secondary replica &apos;{0}&apos;.
        /// </summary>
        internal static string WaitForRoleChange {
            get {
                return ResourceManager.GetString("WaitForRoleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local node is not part of quorum and is therefore unable to process this operation. This may be due to one of the following reasons:\r\n\r\n•   The local node is not able to communicate with the WSFC cluster.\r\n\r\n•   No quorum set across the WSFC cluster.\r\n\r\n For more information on recovering from quorum loss, refer to SQL Server Books Online.\r\n\r\n.
        /// </summary>
        internal static string WizardLaunchFailureQuorumLoss {
            get {
                return ResourceManager.GetString("WizardLaunchFailureQuorumLoss", resourceCulture);
            }
        }
    }
}
