// Copyright (c) Microsoft.
// Licensed under the MIT license.

using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DdlTextParser.sProcNumber")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DdlTextParser.sWord")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sComma")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sEq")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sDoubleQuotedString")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sParam")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sParanthesis")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sSingleQuotedStringSql")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sHexNumber")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sDelim")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sParamValueQI")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sNumber")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sParamValue")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sWord")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessParam.sBraketedWord")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.PostProcessBodyText.get_IdxEnd():System.Int32")]
[module: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.SqlEnumDependencies.GetUrnByQuery(Microsoft.SqlServer.Management.Smo.IDKey):Microsoft.SqlServer.Management.Smo.Urn")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ObjectClass.ObjectOrColumn", MessageId = "ObjectOr")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.FrequencyTypes.OneTime", MessageId = "OneTime")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.Agent.WeekDays", MessageId = "WeekDays")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.WeekDays.WeekDays", MessageId = "WeekDays")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.WeekDays.WeekEnds", MessageId = "WeekEnds")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.WeekDays.EveryDay", MessageId = "EveryDay")]
[module: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.Agent.AgentSubSystem", MessageId = "SubSystem")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerPermissionSetValue.CreateDdlEventNotification", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlGdrDatabaseEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlDatabaseSecurityEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlSchemaEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlFunctionEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlPartitionSchemeEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlRouteEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlRemoteServiceBindingEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlQueueEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlTypeEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlContractEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlApplicationRoleEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlTableViewEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlXmlSchemaCollectionEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlSynonymEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlViewEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlServiceEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlTriggerEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlMessageTypeEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlPartitionEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlPartitionFunctionEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlAuthorizationDatabaseEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlRoleEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlIndexEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlTableEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlStatisticsEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlEventNotificationEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlAssemblyEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlProcedureEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlUserEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlDatabaseLevelEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlSsbEvents", MessageId = "Ssb")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEventSet.DdlSsbEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlAuthorizationServerEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlCertificateEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlGdrServerEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlServerLevelEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlServerSecurityEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlLoginEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEventSet.DdlEndpointEvents", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.IndexKeyType.DriPrimaryKey", MessageId = "Dri")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.IndexKeyType.DriUniqueKey", MessageId = "Dri")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.CatalogPopulationStatus.CrawlinProgress", MessageId = "Crawlin")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.ServerDdlTriggerEvent", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabasePermissionSetValue.AlterAnyDataspace", MessageId = "Dataspace")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabasePermissionSetValue.AlterAnyDatabaseDdlTrigger", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabasePermissionSetValue.AlterAnyFulltextCatalog", MessageId = "Fulltext")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabasePermissionSetValue.CreateFulltextCatalog", MessageId = "Fulltext")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabasePermissionSetValue.CreateDatabaseDdlEventNotification", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabasePermissionSetValue.Showplan", MessageId = "Showplan")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.EndpointEncryptionAlgorithm.Aes", MessageId = "Aes")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.EndpointEncryptionAlgorithm.RC4Aes", MessageId = "Aes")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.EndpointEncryptionAlgorithm.AesRC4", MessageId = "Aes")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.EndpointAuthenticationOrder.NtlmCertificate", MessageId = "Ntlm")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.EndpointAuthenticationOrder.CertificateNtlm", MessageId = "Ntlm")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.EndpointAuthenticationOrder.Ntlm", MessageId = "Ntlm")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.DdlTextParserHeaderInfo", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.DatabaseDdlTriggerEvent", MessageId = "Ddl")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.AgentSubSystem.Ssis", MessageId = "Ssis")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.JobType.MultiServer", MessageId = "Multi")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.CategoryType.MultiServerJob", MessageId = "Multi")]
[module: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Agent.JobServerType.Tsx", MessageId = "Tsx")]
[module: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.Agent.JobStepFlags")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "http_endpoint.xml", MessageId = "logon")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "PrimaryChildren.xml", MessageId = "filename")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "agent_alertsystem.xml", MessageId = "FailSafe")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Process.xml", MessageId = "hostname")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "inc_named_object.xml", MessageId = "isms")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "agent_jobhistory.xml", MessageId = "runtime")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "inc_DbFile.xml", MessageId = "filename")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "ShutDown")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "StandBy")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "filename")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "agent_jobtargetservers.xml", MessageId = "runtime")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "MailServer.xml", MessageId = "username")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "ServerProxyAccount.xml", MessageId = "username")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "MailAccount.xml", MessageId = "username")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Index.xml", MessageId = "rowlocks")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Index.xml", MessageId = "RowLock")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "JobServer.xml", MessageId = "username")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "runtime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "table.xml", MessageId = "sidx")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "table.xml", MessageId = "spart")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "SharedSchedule.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "IndexedColumn.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_job_categories.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_targetserver.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "DatabaseActiveDirectory.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "inc_perm.xml", MessageId = "oc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_operator.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.ProtocolRetrySchedule.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "OLEDBProvider.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Information.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.HostedEventProvider.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.HostedEventProvider.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "CdromDrive.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Job.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "PrimaryChildren.xml", MessageId = "checkprimaryfile")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "PrimaryChildren.xml", MessageId = "dbcc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "temp_table.xml", MessageId = "tempdb")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "ErrorLogText.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_alert_categories.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.VacuumSchedule.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FullTextIndexColumn.xml", MessageId = "syscolumns")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FullTextIndexColumn.xml", MessageId = "sdep")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FullTextIndexColumn.xml", MessageId = "sysdepends")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionConditionEventRule.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionConditionEventRule.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionConditionEventRule.xml", MessageId = "ntext")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionScheduledRule.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionScheduledRule.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionScheduledRule.xml", MessageId = "ntext")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "DatabaseDiagram.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Schedule.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Schedule.xml", MessageId = "uniqueidentifier")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FixedDrive.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "PartitionScheme.xml", MessageId = "sdd")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "RemovableDrive.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "ConfigurationValue.xml", MessageId = "paramvalue")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "File.xml", MessageId = "Fileid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "File.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "File.xml", MessageId = "dbcc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "ltype")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "sch")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "objname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "objid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "indname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "spid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "dbname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "indid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Lock.xml", MessageId = "dbid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "PrimaryFile.xml", MessageId = "checkprimaryfile")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "PrimaryFile.xml", MessageId = "dbcc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_jobhistory.xml", MessageId = "uniqueidentifier")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_ErrorLog.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_ErrorLog.xml", MessageId = "crslogs")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_ErrorLog.xml", MessageId = "deallocate")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level1ExtendedProperty.xml", MessageId = "objname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level1ExtendedProperty.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level2IndexExtendedProperty.xml", MessageId = "parentobjname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level2IndexExtendedProperty.xml", MessageId = "objname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level2IndexExtendedProperty.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "DatabaseOptions.xml", MessageId = "trunc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_alert.xml", MessageId = "uniqueidentifier")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_alert.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NTLogin.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "OLEDBProviderSetting.xml", MessageId = "oprov")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "OLEDBProviderSetting.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Instance.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Instance.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Instance.xml", MessageId = "Adf")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Instance.xml", MessageId = "quotename")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionConditionScheduledRule.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionConditionScheduledRule.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionConditionScheduledRule.xml", MessageId = "ntext")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "dtbmir")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "fg")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Database.xml", MessageId = "dbname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Drive.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.EventField.xml", MessageId = "Mods")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "ServerActiveDirectory.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Member.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "applicationdb")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "quotename")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "cfg")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "ver")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Application.xml", MessageId = "Adf")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "AditionalParameters.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "restore_plan.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "restore_plan.xml", MessageId = "startdate")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.NonHostedEventProvider.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.NonHostedEventProvider.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FullTextCatalog.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FullTextCatalog.xml", MessageId = "ftcatid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.EventChronicleRule.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.EventChronicleRule.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.EventChronicleRule.xml", MessageId = "ntext")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Column.xml", MessageId = "colfk")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionField.xml", MessageId = "Mods")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "ServerProxyAccount.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LogFile.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LogFile.xml", MessageId = "Perc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LogFile.xml", MessageId = "dbcc")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "ErrorLog.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.NotificationClass.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Distributor.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "DatabaseMappings.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "DatabaseMappings.xml", MessageId = "deallocate")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "AgentSubsystems.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "AgentSubsystems.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "AgentSubsystems.xml", MessageId = "deallocate")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Generator.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.Generator.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "MailAccount.xml", MessageId = "servername")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "MailAccount.xml", MessageId = "servertype")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "ProxyAccount.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "fulltext_ErrorLogText.xml", MessageId = "datetime")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "fulltext_ErrorLogText.xml", MessageId = "ctlgid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "RemoteDrive.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "dpub")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "rpcout")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "srvname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "collationcompatible")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "deallocate")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "dataaccess")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "LinkedServer.xml", MessageId = "srvid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "AgentPerfInfo.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobServer.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_operator_categories.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "analysisquery")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "ssis")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "tsql")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "cmdexec")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "queuereader")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "activescripting")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "analysiscommand")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "JobStep.xml", MessageId = "logreader")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionEventRule.xml", MessageId = "nvarchar")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionEventRule.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.SubscriptionEventRule.xml", MessageId = "ntext")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.EventClass.xml", MessageId = "tinyint")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "NS.EventClass.xml", MessageId = "ntext")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level2ExtendedProperty.xml", MessageId = "parentobjname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level2ExtendedProperty.xml", MessageId = "objname")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Level2ExtendedProperty.xml", MessageId = "sysname")]
[module: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "Microsoft.SqlServer.Management.Smo.AuditLevel")]
[module: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Internal.SqlSecureString..ctor(System.IntPtr,System.Int32)")]
[module: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.Internal.SqlSecureString.Join(System.Object,System.Object[],System.Int32,System.Int32):Microsoft.SqlServer.Management.Smo.Internal.SqlSecureString")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "agent_ErrorLog.xml", MessageId = "yyyy")]

[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "inc_system_object.xml", MessageId = "isms")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "inc_system_table_view_sp_udf.xml", MessageId = "isms")]
[module: SuppressMessage("Microsoft.Naming", "CA1701:ResourceStringCompoundWordsShouldBeCasedCorrectly", Scope = "resource", Target = "Job.xml", MessageId = "protecttype")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Job.xml", MessageId = "sysadmin")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Job.xml", MessageId = "uid")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Job.xml", MessageId = "sysprotects")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "Job.xml", MessageId = "protecttype")]

// used in debug routines
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.DatabaseLevel.CleanupFilter():System.Void", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.SqlEnumDependencies.EnumDependencies(System.Object,Microsoft.SqlServer.Management.Smo.DependencyRequest):Microsoft.SqlServer.Management.Smo.DependencyChainCollection", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.SqlObjectBase.RetrieveParentRequestLinks(Microsoft.SqlServer.Management.Smo.SqlRequest):System.Void", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.NSDatabaseLevel.CleanupFilter():System.Void", MessageId = "System.Int32.ToString")]
[module: SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", Scope = "member", Target = "Microsoft.SqlServer.Management.Smo.SqlEnum.Res.GetString(System.String,System.Object[]):System.String", MessageId = "System.String.Format(System.String,System.Object[])")]
[module: SuppressMessage("Microsoft.Naming", "CA1703:ResourceStringsShouldBeSpelledCorrectly", Scope = "resource", Target = "FullTextCatalog.xml", MessageId = "fti")]
