name: pr-validation

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v2
      with:
        global-json-file: global.json
    - run: |
        outfolder=`pwd`/out 
        dotnet build dirs.proj -p:baseoutputpath=$outfolder
    - uses: actions/upload-artifact@v3
      with: 
        name: tests
        path: out/Debug/netcoreapp3.1
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        sqlImage: ['2017','2019']
    steps:
    - uses: actions/checkout@v2
    - name: Download build files
      uses: actions/download-artifacts@v3
      with: 
        name: tests
        path: tests
    - name: Copy toolsconnectioninfo
      run: cp .github/workflows/ToolsConnectionInfo.xml .
    - name: Install SQL Server
      run: |
        export SAPASSWORD=$(date +%s|sha256sum|base64|head -c 32)
        echo "SAPASSWORD=$SAPASSWORD" >> $GITHUB_ENV
        docker run -m 2GB -e ACCEPT_EULA=1 -d --name sql -p:1433:1433 -e SA_PASSWORD=$SAPASSWORD mcr.microsoft.com/mssql/server:${{ matrix.sqlImage }}-latest
        sleep 10
    - name: Run tests against Linux SQL
      run: dotnet test tests/Microsoft.SqlServer.Test.Smo.dll -logger:"trx;LogFilePrefix=SmoTests" --filter TestCategory!=Staging&TestCategory!=Legacy
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with: 
        name: test-results-${{ matrix.sqlImage }}
        path: test-results
      if: ${{ always() }}
